---
 
 - hosts: all
   become: true
   tasks:

   - name: install updates (Ubuntu)
     tags: always
     apt:
       state: latest
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

 - hosts: web_servers
   become: true
   tasks:

   - name: install apache and php for Ubuntu servers
     tags: always
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"

   - name: copy files
     tags: apache,apache2,httpd
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: guest
       group: guest
       mode: 0644
